package:
  name: agd
  version: 0.0.2
  
source:
  path: ../

requirements:
  build:
#    - python
    noarch: python # Cannot get this to work, set several versions in conda_build_config.yaml instead

  run:
   - python
   - numpy
   - scipy
#   - itertools
#   - importlib
#   - functools
#   - os
#   - math
#   - copy
